# Generated by Django 2.2 on 2019-05-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190524_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
    ]
