# Generated by Django 2.2 on 2019-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190526_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
    ]
